# Site settings
title: The Animal Library
email: thesittinghun@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of low-poly digital animals, viewable in 3D.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: ""
twitter_username: atthar_mirza
github_username:  attharmirza

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
sass:
  sass_dir: _styles
  style: compressed
collections:
  animals:
    title: Animals
    output: true
defults:
- scope:
    path: ""
    type: animals
  values:
    layout: animal
    title:
    category:
pagination:
  enabled: true
  collection: 'animals'
  per_page: 6
  permalink: '/index/page:num.html'


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
